name: create-release-upload

on: 
  push:
    tags:
    - 'v*'

jobs:
  create_releases:
    name: create-releases
    runs-on: ubuntu-20.04
    outputs:
      release_url: ${{ steps.output_url.outputs.upload_url }}

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: true
      continue-on-error: true
    - name: Get release
      if: steps.create_release.outcome == 'failure'
      id: get_release
      uses: bruceadams/get-release@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: output url
      id: output_url
      run: |
        echo "upload_url=${{steps.get_release.outputs.upload_url}}${{steps.create_release.outputs.upload_url}}" >> $GITHUB_OUTPUT

  upload-object-windows:
    name: upload-object-win
    needs: create_releases
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2019', 'windows-2022']
        shared: ['on', 'off']
        include:
          - os: 'windows-2019'
            bin: vs2019
          - os: 'windows-2022'
            bin: vs2022
          - shared: 'on'
            suffix: ''
          - shared: 'off'
            suffix: '-static'

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: output url
      id: get_url
      run: echo "upload_url=${{ needs.create_releases.outputs.release_url }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      shell: bash
    - name: dump version
      env:
        version: ${{ steps.get_version.outputs.VERSION }}
      run: echo "version=${version}"
      shell: bash
    - name: create folder
      run: |
        cd cfd-sys/cfd-cmake
        mkdir dist
    - name: cmake-build
      run: |
        cd cfd-sys/cfd-cmake
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_SHARED=${{ matrix.shared }} -DENABLE_CAPI=on -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DCMAKE_INSTALL_PREFIX="./dist"
        cmake --build build --parallel 2 --config Release
        cd ../..
      timeout-minutes: 20
    - name: cmake-install
      run: |
        cd cfd-sys/cfd-cmake
        cmake --install build
        cd dist
        del /F /Q cmake\wallycore-*
        del /F /Q lib\wallycore.*
        del /F /Q lib\libwallycore.*
        del /F /Q lib\pkgconfig\wallycore.pc
      shell: cmd
    - name: create archive file
      run: |
        cd cfd-sys/cfd-cmake
        cd dist
        Compress-Archive -Path ./* -DestinationPath ../cfd.zip
        cd ..
        echo "---- dump zip file ----"
        dir .
    - name: Upload Release Asset
      id: upload-release-asset 
#      if: success()
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./cfd-sys/cfd-cmake/cfd.zip
        asset_name: cfd-sys-${{ steps.get_version.outputs.VERSION }}-win-${{ matrix.bin }}${{ matrix.suffix }}-x86_64.zip
        asset_content_type: application/zip

  upload-object-ubuntu:
    name: upload-object-ubuntu
    needs: create_releases
    runs-on: ubuntu-${{ matrix.os_ver }}.04
    strategy:
      fail-fast: false
      matrix:
        os_ver: [20, 22]
        bin: [gcc, gcc-static]
        include:
          - bin: gcc
            shared: on
          - bin: gcc-static
            shared: off

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
    - name: cmake-build
      run: |
        cd cfd-sys/cfd-cmake
        mkdir dist
        mkdir build
        cd build
        cmake .. -DENABLE_SHARED=${{ matrix.shared }} -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DCMAKE_BUILD_TYPE=Release -DTARGET_RPATH="/usr/local/lib"
        cd ..
        cmake --build build --parallel 2 --config Release
        cd build
        sudo make install DESTDIR=../dist
        cd ../../..
    - name: create archive file
      run: |
        cd cfd-sys/cfd-cmake
        cd dist
        zip -r cfd.zip usr
        echo "---- dump zip file ----"
        ls -l
    - name: output url
      id: get_url
      run: echo "upload_url=${{ needs.create_releases.outputs.release_url }}" >> $GITHUB_OUTPUT
    - name: Upload Release Asset Ubuntu
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./cfd-sys/cfd-cmake/dist/cfd.zip
        asset_name: cfd-sys-${{ steps.get_version.outputs.VERSION }}-ubuntu${{ matrix.os_ver }}04-${{ matrix.bin }}-x86_64.zip
        asset_content_type: application/zip

  upload-object-alpine:
    name: upload-object-alpine
    needs: create_releases
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        alpine: ['3.14', '3.15', '3.16', '3.17']

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
    - name: list
      run: ls -a $GITHUB_WORKSPACE
    - name: docker setup 3.14
      if: matrix.alpine == '3.14'
      uses: docker://alpine:3.14
      with:
        entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
    - name: docker setup 3.15
      if: matrix.alpine == '3.15'
      uses: docker://alpine:3.15
      with:
        entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
    - name: docker setup 3.16
      if: matrix.alpine == '3.16'
      uses: docker://alpine:3.16
      with:
        entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
    - name: docker setup 3.17
      if: matrix.alpine == '3.17'
      uses: docker://alpine:3.17
      with:
        entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
    - name: create archive file
      run: |
        echo "---- dump output data ----"
        ls -l $GITHUB_WORKSPACE/dist/usr/local/*
        mkdir -p /tmp/cfd
        sudo chmod 777 /tmp/cfd
        sudo chown runner /tmp/cfd
        sudo cp -r $GITHUB_WORKSPACE/dist/usr /tmp/cfd
        cd /tmp/cfd
        sudo zip -r /tmp/cfd/cfd.zip usr
        sudo chmod 777 /tmp/cfd/cfd.zip
        sudo chown runner /tmp/cfd/cfd.zip
        sudo cp -rp /tmp/cfd/cfd.zip $GITHUB_WORKSPACE/dist/cfd.zip
        echo "---- dump zip file ----"
        sudo ls -l /tmp/cfd
    - name: output url
      id: get_url
      run: echo "upload_url=${{ needs.create_releases.outputs.release_url }}" >> $GITHUB_OUTPUT
    - name: Upload Release Asset
      id: upload-release-asset 
#      if: success()
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: /tmp/cfd/cfd.zip
        asset_name: cfd-sys-${{ steps.get_version.outputs.VERSION }}-alpine${{ matrix.alpine }}_x86_64.zip
        asset_content_type: application/zip

  upload-object-macos:
    name: upload-object-macos
    needs: create_releases
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]
        xcode_version: ['11.7', '12.5.1', '13.4.1']
        shared: [on, off]
        include:
          - shared: on
            suffix:
          - shared: off
            suffix: -static
        exclude:
          - xcode_version: '11.7'
            os: macos-12
          - xcode_version: '12.5.1'
            os: macos-12
          - xcode_version: '13.4.1'
            os: macos-11

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
    - name: cmake-build
      run: |
        cd cfd-sys/cfd-cmake
        mkdir dist
        mkdir build
        cd build
        cmake .. -DENABLE_SHARED=${{ matrix.shared }} -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DCMAKE_BUILD_TYPE=Release -DTARGET_RPATH="/usr/local/lib"
        cd ..
        cmake --build build --parallel 2 --config Release
        cd build
        sudo make install DESTDIR=../dist
        cd ../../..
    - name: create archive file
      run: |
        cd cfd-sys/cfd-cmake
        cd dist
        zip -r cfd.zip usr
        echo "---- dump zip file ----"
        ls -l
        cd ../../..
        mv ./cfd-sys/cfd-cmake/dist/cfd.zip ./cfd-sys-${{ steps.get_version.outputs.VERSION }}-osx-xcode${{ matrix.xcode_version }}${{ matrix.suffix }}-x86_64.zip
    - name: Upload Release Asset Ubuntu
      uses: softprops/action-gh-release@v1
      with:
        files: cfd-sys-${{ steps.get_version.outputs.VERSION }}-osx-xcode${{ matrix.xcode_version }}${{ matrix.suffix }}-x86_64.zip
