name: create-release-upload

on:
  push:
    tags:
      - 'v*'

jobs:
  create_releases:
    name: create-releases
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        shell: bash
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          prerelease: true
        continue-on-error: true

  upload-object-windows:
    name: upload-object-win
    needs: create_releases
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2019', 'windows-2022']
        shared: ['on', 'off']
        include:
          - os: 'windows-2019'
            bin: vs2019
          - os: 'windows-2022'
            bin: vs2022
          - shared: 'on'
            suffix: ''
          - shared: 'off'
            suffix: '-static'

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        shell: bash
      - name: dump version
        env:
          version: ${{ steps.get_version.outputs.VERSION }}
        run: echo "version=${version}"
        shell: bash
      - name: Get the asset name
        id: asset_name
        run: echo "ASSET_NAME=cfd-sys-${{ steps.get_version.outputs.VERSION }}-win-${{ matrix.bin }}${{ matrix.suffix }}-x86_64.zip" >> $GITHUB_OUTPUT
        shell: bash
      - name: create folder
        run: |
          cd cfd-sys/cfd-cmake
          mkdir dist
      - name: cmake-build
        run: |
          cd cfd-sys/cfd-cmake
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_SHARED=${{ matrix.shared }} -DENABLE_CAPI=on -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DCMAKE_INSTALL_PREFIX="./dist"
          cmake --build build --parallel 2 --config Release
          cd ../..
        timeout-minutes: 20
      - name: cmake-install
        run: |
          cd cfd-sys/cfd-cmake
          cmake --install build
          cd dist
          del /F /Q cmake\wallycore-*
          del /F /Q lib\wallycore.*
          del /F /Q lib\libwallycore.*
          del /F /Q lib\pkgconfig\wallycore.pc
        shell: cmd
      - name: create archive file
        run: |
          cd cfd-sys/cfd-cmake
          cd dist
          Compress-Archive -Path ./* -DestinationPath ../../../${{ steps.asset_name.outputs.ASSET_NAME }}
          cd ..
          echo "---- dump zip file ----"
          dir .
      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.asset_name.outputs.ASSET_NAME }}

  upload-object-ubuntu:
    name: upload-object-ubuntu
    needs: create_releases
    runs-on: ubuntu-${{ matrix.os_ver }}.04
    strategy:
      fail-fast: false
      matrix:
        os_ver: [20, 22, 24]
        bin: [gcc, gcc-static]
        include:
          - bin: gcc
            shared: on
          - bin: gcc-static
            shared: off

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Get the asset name
        id: asset_name
        run: echo "ASSET_NAME=cfd-sys-${{ steps.get_version.outputs.VERSION }}-ubuntu${{ matrix.os_ver }}04-${{ matrix.bin }}-x86_64.zip" >> $GITHUB_OUTPUT
        shell: bash
      - name: cmake-build
        run: |
          cd cfd-sys/cfd-cmake
          mkdir dist
          mkdir build
          cd build
          cmake .. -DENABLE_SHARED=${{ matrix.shared }} -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DCMAKE_BUILD_TYPE=Release -DTARGET_RPATH="/usr/local/lib"
          cd ..
          cmake --build build --parallel 2 --config Release
          cd build
          sudo make install DESTDIR=../dist
          cd ../../..
      - name: create archive file
        run: |
          cd cfd-sys/cfd-cmake
          cd dist
          zip -r cfd.zip usr
          echo "---- dump zip file ----"
          ls -l
      - name: rename asset
        run: mv ./cfd-sys/cfd-cmake/dist/cfd.zip ${{ steps.asset_name.outputs.ASSET_NAME }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.asset_name.outputs.ASSET_NAME }}

  upload-object-alpine:
    name: upload-object-alpine
    needs: create_releases
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        alpine: ['3.17', '3.18', '3.19', '3.20']

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Get the asset name
        id: asset_name
        run: echo "ASSET_NAME=cfd-sys-${{ steps.get_version.outputs.VERSION }}-alpine${{ matrix.alpine }}_x86_64.zip" >> $GITHUB_OUTPUT
        shell: bash
      - name: list
        run: ls -a $GITHUB_WORKSPACE
      - name: docker setup 3.17
        if: matrix.alpine == '3.17'
        uses: docker://alpine:3.17
        with:
          entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
      - name: docker setup 3.18
        if: matrix.alpine == '3.18'
        uses: docker://alpine:3.18
        with:
          entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
      - name: docker setup 3.19
        if: matrix.alpine == '3.19'
        uses: docker://alpine:3.19
        with:
          entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
      - name: docker setup 3.20
        if: matrix.alpine == '3.20'
        uses: docker://alpine:3.20
        with:
          entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
      - name: create archive file
        run: |
          echo "---- dump output data ----"
          ls -l $GITHUB_WORKSPACE/dist/usr/local/*
          mkdir -p /tmp/cfd
          sudo chmod 777 /tmp/cfd
          sudo chown runner /tmp/cfd
          sudo cp -r $GITHUB_WORKSPACE/dist/usr /tmp/cfd
          cd /tmp/cfd
          sudo zip -r /tmp/cfd/cfd.zip usr
          sudo chmod 777 /tmp/cfd/cfd.zip
          sudo chown runner /tmp/cfd/cfd.zip
          sudo cp -rp /tmp/cfd/cfd.zip $GITHUB_WORKSPACE/dist/cfd.zip
          echo "---- dump zip file ----"
          sudo ls -l /tmp/cfd
      - name: rename asset
        run: mv /tmp/cfd/cfd.zip ${{ steps.asset_name.outputs.ASSET_NAME }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.asset_name.outputs.ASSET_NAME }}

  upload-object-macos:
    name: upload-object-macos
    needs: create_releases
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-13', 'macos-14', 'macos-15']
        shared: [on, off]
        include:
          - os: macos-13
            xcode: '14.3.1'
            arch: 'x86_64'
          - os: macos-14
            xcode: '15.4'
            arch: 'arm64'
          - os: macos-15
            xcode: '16.1'
            arch: 'arm64'
          - shared: on
            suffix: ''
          - shared: off
            suffix: '-static'

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: cmake-build
        run: |
          cd cfd-sys/cfd-cmake
          mkdir dist
          mkdir build
          cd build
          cmake .. -DENABLE_SHARED=${{ matrix.shared }} -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DCMAKE_BUILD_TYPE=Release -DTARGET_RPATH="/usr/local/lib"
          cd ..
          cmake --build build --parallel 2 --config Release
          cd build
          sudo make install DESTDIR=../dist
          cd ../../..
      - name: create archive file
        run: |
          cd cfd-sys/cfd-cmake
          cd dist
          zip -r cfd.zip usr
          echo "---- dump zip file ----"
          ls -l
          cd ../../..
          mv ./cfd-sys/cfd-cmake/dist/cfd.zip ./cfd-sys-${{ steps.get_version.outputs.VERSION }}-osx-xcode${{ matrix.xcode }}${{ matrix.suffix }}-${{ matrix.arch }}.zip
      - name: Upload Release Asset Ubuntu
        uses: softprops/action-gh-release@v2
        with:
          files: cfd-sys-${{ steps.get_version.outputs.VERSION }}-osx-xcode${{ matrix.xcode }}${{ matrix.suffix }}-${{ matrix.arch }}.zip
